---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: synology
  description: synology ds218+
  annotations:
    # backstage.io/techdocs-ref: dir:.
    github.com/project-slug: tyriis/home-ops
  links:
    - url: https://synology.techtales.io
      title: Synology dashboard
      icon: dashboard
      type: admin-dashboard
  tags:
    - nas
    - nfs
    - backup
    - storage
    - s3
spec:
  owner: home-ops
  domain: home
  type: storage
  lifecycle: production
  system: synology
