---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../kubernetes/main/apps/observability/grafana/instance/datasource.yaml
  - ../../../../../../kubernetes/main/apps/observability/grafana/instance/grafana.yaml
  # - ../../../../../../kubernetes/main/apps/observability/grafana/instance/service-monitor.yaml
patches:
  - path: grafana.yaml
