---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: argo-workflows
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/argo/argo-workflows?modal=values
    singleNamespace: true

    controller:
      image:
        registry: quay.io
        repository: argoproj/workflow-controller
        tag: v4.1.2@sha256:466192f538abfe750157c5bb5c0b883137b19f67af27c5636ab15bc853c96668
      parallelism: 20
      resourceRateLimit:
        limit: 10
        burst: 1

      namespaceParallelism: 10

      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

    executor:
      image:
        registry: quay.io
        repository: argoproj/argoexec
        tag: v4.1.2@sha256:4a7b9a9859b63e7aea7927c69fc336a5ef07f8dbea91ae2e175cda8788d972e9

    server:
      enabled: true
      image:
        registry: quay.io
        repository: argoproj/argocli
        tag: v4.1.2@sha256:4e47842692bb72705cb8179279989d26039e5ed318f8fa7cc77df1b246d97c67
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

      extraArgs:
        - --auth-mode=sso

      sso:
        enabled: true
        issuer: https://id.techtales.io
        redirectUrl: https://argo-workflows.techtales.io/oauth2/callback
        clientId:
          name: argo-workflows-pocketid
          key: client-id
        clientSecret:
          name: argo-workflows-pocketid
          key: client-secret
        scopes:
          - groups
          - email
          - profile
        rbac:
          enabled: true

    workflow:
      serviceAccount:
        create: true
        name: argo-workflow
      rbac:
        create: true
    metricsConfig:
      enabled: false
    serviceMonitor:
      enabled: true
