---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: argo-workflows
      version: 1.0.24
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/argo/argo-workflows?modal=values
    singleNamespace: true

    controller:
      image:
        registry: quay.io
        repository: argoproj/workflow-controller
        tag: v4.1.0@sha256:183327f1bfb7d61570114e092df8bf6d8eff4417c57d2dc88e95c82c2d1c527c
      parallelism: 20
      resourceRateLimit:
        limit: 10
        burst: 1

      namespaceParallelism: 10

      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

    executor:
      image:
        registry: quay.io
        repository: argoproj/argoexec
        tag: v4.1.0@sha256:12424cb9fd3eaedd3e8e1a471905a411e710ae2ddb83d9679fd246a4330a229b

    server:
      enabled: true
      image:
        registry: quay.io
        repository: argoproj/argocli
        tag: v4.1.0@sha256:9a65f616eb2cafcbed895f19cec80781c3f9641d7e0bda3dfbb867be6ca87ace
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

      extraArgs:
        - --auth-mode=server

    workflow:
      serviceAccount:
        create: true
        name: argo-workflow
      rbac:
        create: true
    metricsConfig:
      enabled: false
    serviceMonitor:
      enabled: true
