---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: argo-workflows
      version: 0.47.3
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/argo/argo-workflows?modal=values
    singleNamespace: true

    controller:
      image:
        registry: quay.io
        repository: argoproj/workflow-controller
        tag: v4.0.0@sha256:dd288d8e75e435cfa0326a8d2836a836bf77feee3bffe40f88c3847a69b1138a
      parallelism: 20
      resourceRateLimit:
        limit: 10
        burst: 1

      namespaceParallelism: 10

      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

    executor:
      image:
        registry: quay.io
        repository: argoproj/argoexec
        tag: v4.0.0@sha256:ef934dbe7047a989129f84426a81b5e6e97bfcc1477c9dbabb175bba639676c0

    server:
      enabled: true
      image:
        registry: quay.io
        repository: argoproj/argocli
        tag: v4.0.0@sha256:c115f41afb5ef500437aad79f3112a224bf243d8f7934eed3f6523f7125df664
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

      extraArgs:
        - --auth-mode=server

    workflow:
      serviceAccount:
        create: true
        name: argo-workflow
      rbac:
        create: true
    metricsConfig:
      enabled: false
    serviceMonitor:
      enabled: true
