---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: argo-system
  annotations:
    workflows.argoproj.io/rbac-rule: "'privileged-users' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-readonly
  namespace: argo-system
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"