---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/clusterrole_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-server-cluster-template
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
    verbs:
      - get
      - list
      - watch
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: argo-system
  annotations:
    workflows.argoproj.io/rbac-rule: "'privileged-users' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-readonly
  namespace: argo-system
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
