---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/networkpolicy.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dragonfly-allow-metrics
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
  policyTypes:
    - Ingress
  ingress:
    # Allow dragonfly-operator to perform health checks on port 9999
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly-operator
      ports:
        - protocol: TCP
          port: 9999
    # Allow kube-prometheus to scrape Dragonfly metrics on port 9999
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9999
