---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          runner:
            token: "{{ .RUNNER_TOKEN }}"
            instance: https://git.utility.techtales.io
            labels: ["forgejo:docker"]
  dataFrom:
    - extract:
        key: infra/kubernetes/main/forgejo-runners/${APP}
