---
creation_rules:
  - path_regex: kubernetes/utility/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
  - path_regex: 'talos/.*\.sops\.ya?ml$'
    age: >-
      age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
  - path_regex: 'docker/red/.*/sops\.env$'
    age: >-
      age16pcjw9pvhx2lnx382hrgcpydpjvjz6r8u22wflm228cakedrlgdqzlwx4s
  - path_regex: 'docker/synology/.*/sops\.env$'
    age: >-
      age1tcjhmd54y4nx9mpwld5fu0laav06wwjscvq4adqfquxtj4fg7a7q2s95sc
