# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-bifrost
stringData:
    token: ENC[AES256_GCM,data:Xnq2xVsy7tTvcdLgTiJyljxc6eV/LmVZPgUfXdKx2gKuy92LKXi4VFpMTzs5Hoc5GCKCN2TJPfJd2rHeHy2OwQ==,iv:URHmy1mty4rM3lLz+76sCHUhnNFBgSEvnHWXhDUXXo0=,tag:/iNV4m6ns77ChA8iWVZfIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcG82WmNPOWNxQ2RxMUFZ
            eERBem1BNmNPS1VEUnhWR2JmeFVsNFdSaWtNCmFpVjBZcDJ0V2RuTTJvSmhtUm9k
            eTJVM2FHMXI0MmVQcXhkeS96M1JIOW8KLS0tIHhXTWFmV0pyTitGQVZESC83ZkVK
            emdNMTYvRzNEWmVUK3F5K2lOYUtNd1EKzMGBUCjIJFG89dWJZWpkM4LEqjJ255kO
            kSbCxZdz7lVNvZvrLO9Ii9C8IosulMqmSThZsUFJvraIlKYaE+tfxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:56Z"
    mac: ENC[AES256_GCM,data:e4xYsjvGbZaP+kd8+qzhInMUDyCDOLwjf2zosm20J5epGhjaabpilCUoUDdEhztyOOvGe/X0oqBSLumsqKQgjGZPxyjK72LTs7A3xEcSbx8oXhcPzoirHLRvtIR/R/fj50YXirGIpfGYJxGweTohag6DDnJ9m4fEHcKJo/jg3jw=,iv:3xvmTFV/aJ6LR5kIQ+Y9bDtHGVlHKeFkIf0L+MtZwJo=,tag:E6nV9bad9DCOol7BiqhObA==,type:str]
    version: 3.13.3
