# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-workstation
stringData:
    token: ENC[AES256_GCM,data:TupOyprKrbNLl2/aqxqrYsNtH4dwt2F0TF96fqFpssE8gXTxU2eDesQcYCj+I9CeVnBmmNXMmXxWKVfTGfNvyw==,iv:cTxIorJZELZcj9jmxm+FkHR9TiVTbLwJ+OSdzBY/KWM=,tag:UcvHMKM+uEGaHrdiBOEEkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMmU2NXM5YW94TUdaS2Zw
            MHZoYmtqbFU5RUlHUDN3Z2oxbk42Q25BQ0N3CmJDLzJ4aklkTlZ6TkxFc2NKWDMv
            azZ0YzJRYTBGeUVGamM0WmtKWW5VbWsKLS0tIFJ4MEVQZ09JRU1rNGhsZlJpQTVs
            NmNnYVBIb1MxWGJEZFNqYXRHdVFNOTgKR8gGVXclqKVoxB+GVAR/P/f9QRLIievl
            jE/1c/DdP6yQeMcMvuwA2RR5wS7Pmz/CflR8HEOb4kvyqQ50lM3/SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:57Z"
    mac: ENC[AES256_GCM,data:taE5ebg0guivzLoFiKO8x5GUMMs1ZOwv2Pn2Eur0xVAU7Ju9eDUjcAOgxZa8CkRRBqfuNbJy+1FBjAghfWXalT8N5Wx8WQzROO3CNHETuT69YC4gGAiM2tZc0dKLh0VjY3VHjW/jvLrhM8iVeW2QjBmVRH0dTJIEWXIbEqXtxw4=,iv:csbM4m/68nLlPGWX1FWCNnIlESDfQFEK1xOEL4YtkR8=,tag:E2I0jlmzec0ogByKrlbuWg==,type:str]
    version: 3.13.3
