# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-remote
stringData:
    token: ENC[AES256_GCM,data:45rD6LDXDBZI5NvzOwwrJOiLBoCyN36hAooQS+Z0i+Ius0PT2sN63fYaYrLuY41e1d+0lDRdu9JDOTd8rRpcKg==,iv:UmEe9TOdhkZ/6OKZ6sz6m9qtCbNCqsEr9C+lU5Ps35Y=,tag:nH5YCCF3LYr6SewSDp1TGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbzJYcFlMODlGRHJFTlVY
            Yld0TlVFZFZVa0Vua3BVWlhwN2U2TUUvMmpjCktmVGpEb0ZkZkdrSW50YUZiTDlT
            WVNrRHFXK0Y2dnJPL2xFRnhxdjg1cWMKLS0tIFcvZmwxR1krenRDZENuOFZkQnBP
            YXJycjRjTURtQVQrRkhpZXVhdEhSUmcKrZYKtxflxlfslSYRcmbjqQMQsAcCvlY/
            EVekSERN96mi7Qf2kkiMv0I7CTv5JZIu027DZLVGydovAso4qTv4wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:57Z"
    mac: ENC[AES256_GCM,data:r7G+abSU1BquEk8TjsXdd2dXuqLM8XIYa3NoatKCNEk7VbfFtyAhchvdPR/Ht1waHOeziWTkwF+SATFjhR+rRPNoElhqCVdCZ1+qpshLCCNw4wSj7j6ZP36tmNoC7hotA79oP/GfUseAkCIyffpTqeW4YqLUk1dEmYffY1aCSd0=,iv:NaPTtisZtGn7CFtrCMh5tbygZ+OPun14YMIYjth9uNA=,tag:JySmVx20JjfkQ0DbR3F05Q==,type:str]
    version: 3.13.3
