# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-nas
stringData:
    token: ENC[AES256_GCM,data:aS/sqeKaMu5xw4mejUoZkojPzLu+fcqju9N8qimCACSm0emQQQT1jkMPchpDuu9i/UDxXVt0/4YMBcZtc3WJTw==,iv:hkk777SHwo8Z4gg9C2LDvgrHz1xsZRbvvGtNwwSptsU=,tag:yE5+vpODNCpSt2K8RYhznw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK2JkVnVxUnR0aE1vRGhX
            YWdDODJ2NW83SUNxL05MYUFyQXU5MDNsMDFVCkEyQTFqS1dqNE9OZWx2ZVdZYkRS
            Rys1T1N3MGJUS3cxUUFRTTIxU2oyTnMKLS0tIDAyLzYxUWVvS3RYbEh3SHJ1REQw
            RUNMYXZ1U1JDZ2ZWMm1yQllYSEg1TEEK/dqaGfJ5x5d0QVJryIbR2KpxdF7HFN4z
            Ii4ru3nVss5WaiADgVcRUM7zCFBaNPwR20BPFW1g4bYtnnXdtal0Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:56Z"
    mac: ENC[AES256_GCM,data:ChGjS4/HQKTIMOl+jB/vQZSKh2pdQJ8NovG6XQBAs3rTombx4Kli9Q1u9OKh984No5Zyy5XpHWfOFw+JWKyxz7imnZuWdB4W/6OPv/SUn3w6JxLPwGtdQS35ooCkB0Dg1FoP+mC0KIFQ+9DJ35c8jGnAwM1K2Q7+BTGj1buG0Qs=,iv:+RgdqZfhbH7vkmtKsPZ/NQqHBXpoRgnwPSaHABRrP58=,tag:5dzsmJ6SJr8dZiqGHVrarg==,type:str]
    version: 3.13.3
