# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-ms01
stringData:
    token: ENC[AES256_GCM,data:RXQfRyfBbhtz5hAcXuCgbhty2lTOzb9spV8pg1wYjSHVy7+IpEjJyGwkAyHehogtsTHlbhKQLZVb1N6QD/uP2A==,iv:3QrZgkgpN6k94CD6edMpx0npgmzJO2jJ7RfQi4guKZ0=,tag:jwwjZwuzie7kEAn73q5O6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2tnVnFvdlNZMFJjMWFS
            bHBDTXhXNGpybVZncW40OE5pM3A2ajFoM21ZClJoMjJRQ2tROURBWGtGNG5uZFJP
            elcxa1YxV3lHb0VvL2dsV1dnMDZQa0kKLS0tIHJacDNpZ2JBSndwbXFLd2lzeFg2
            eHhETVdBQmh1ajJvU0crVFhEZHY3SjAKrcsXRGZkjzDj7L8D7KIE7m1L9/ic9xlJ
            IIDGKoaytHZPaqj34BwHupD7lka9nRRQK4IVIg3D2PvWTCFhpupdcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:56Z"
    mac: ENC[AES256_GCM,data:KG4AX8WAm3E7a0P/Sy6M9gYQCNAVIRGuTC//Ukf4RPKIjkx4V0SDcQ7mW/BaPIioaG2k2l0gRrgW0tNTprwduiNqZPmmuX1fz34urccy5SCH9AGbLAdqT9TaH1P2ZXxrSC7++FuvM4KbG+kwUZbIUuh6xaf+KW9+q+yePdojk3s=,iv:4TwdrbdRmxtwRSbe15e3HYg97HB3K1zx+kLqO8fRFy8=,tag:sqn3KeaW8aAsVMHg1eYHkg==,type:str]
    version: 3.13.3
