# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-grafana
stringData:
    token: ENC[AES256_GCM,data:qBdHAfxr+4vdyQj1HB0tc05IgUXdpMbb5W5VuCF0vEjpel6eQVRES7emnF9r+AfJN8iOBAw41AVpKaEcKsrnKQ==,iv:/upI6lAevYnr51+n0ptxADrcKkxbRP6+N6EH6AOfcSg=,tag:XNPtqEH7QSMY18EkmALrbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S1B6TnM0YUExS3lVN2NF
            amRWbytlRWE2QlpuSXo5RUVEZ0pXNzhuRVhBClhGU1EwNGVRekErRTllVEc3TnFQ
            cTBSQklNOThKL2xyd080eGxpbTZvSDAKLS0tIGcwYi9LU0MwOS91dGFlRnlnOWlN
            SmViVWhSZXJjMXJ1QkpkUzRoejZLVmcK8AdF36nWry0BnsI3WK43PGtYRyNbPR+Y
            nA52sU8h59ETZQnHZAubacTK27/6GsUXGVANpVy7MAMNZ673tm4MGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:57Z"
    mac: ENC[AES256_GCM,data:aemAzUu5F4wCuxjhUmxPrbPkxqdQnWp4wqdVkkFjVYPENMlGtCxT8xQd5jCbsXfCcTWKe2Apm25NAG2emxWiVL9vq7E4FGZ0Pp+qULPt1x0ZHzukpYopB+DDOzml/aYcZhSdUqujYLe+cVZ3Fz65MiAY0TWbnaUPoInEPi+wEhM=,iv:0mcwPkgvA5ZfsTLRRPtAQ0NxAPQUK1zOzT6CO64qKFE=,tag:cCYiabvwbPHXi1QUwTR/0Q==,type:str]
    version: 3.13.3
