# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-utility
stringData:
    token: ENC[AES256_GCM,data:VIyBMFethnFsYIv+TPtzN5RN39o94UK016ze8cxk1QoCdqXDQjx1palSoJVkEoJkRdFALrP3OgHaI+vntDh98Q==,iv:NIh44+1IPVLHeS/SCnTuuQd54gzzQXzZj9frChliQqA=,tag:/e4A7ycpxYnNlo1l399jFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWowY3EycmlhbWU2c0dV
            RmpwZWtyMDJoOVQxRE5uRlpaN0ZMU0w3MFdBCnBwWGVCemJMbTFOYkJYcGw3bXRC
            UXZXK2FPNW5zb3AxQmQ3b21RQjRrU3cKLS0tIHczKytHUmZDNGlPVDcrbkY5Wm5p
            RWk1QmFxRm1aZGxIcG4wbUtGMTN6VmMKAap/AOFSFnHhb+wBeIjfIQaeOwf1uWmV
            TBp9Aumib1Bnq7m8KorWHTaZdeVgYu8h2OqvyPdjZbYJjGEWpzXfew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:09:56Z"
    mac: ENC[AES256_GCM,data:Go34253DdAHn08i8xGpvoN4MCStrcaSQ7IfpfPsBiE82TvgajxpAPTQUhJAvjTnMUw96rxrSY35ucDOEWSarPSFqUbwn2c3V6az/YkbDhMMtP6FHYEtXjY9W3Mh6DFr4FCjqUsz6RfvK/7yGwwvlpkshWIwlOB2Y+j3GKEAIjRc=,iv:4sQ2kVkXRvqoJmHtfGJjeuuE0ISfvvNd6mMU5vTGxQU=,tag:DlFQKPduAhAyejBOv9Fu/Q==,type:str]
    version: 3.13.3
