---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app dragonfly
  labels:
    app.kubernetes.io/name: *app
spec:
  podMetricsEndpoints:
    - interval: 30s
      port: admin
  podTargetLabels: ["app.kubernetes.io/name"]
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
