---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-litestream
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITESTREAM_ACCESS_KEY_ID: "{{ .LITESTREAM_ACCESS_KEY_ID }}"
        LITESTREAM_SECRET_ACCESS_KEY: "{{ .LITESTREAM_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/secops/pocket-id/litestream

---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-encryption
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/secops/pocket-id/encryption
