---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: pocket-id-litestream-config
    files:
      - litestream.yml=./litestream.yaml
generatorOptions:
  disableNameSuffixHash: true
