---
validation:
  interval: 1h
dbs:
  - path: /app/data/pocket-id.db
    replica:
      type: s3
      bucket: litestream
      path: pocket-id/pocket-id.db
      endpoint: https://s3.techtales.io
      force-path-style: true
      # - type: file
      #   path: /backup/litestream/pocket-id
      #   snapshot:
      #     interval: 1h
      #     retention: 168h
