---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name talosctl-oidc-ca
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ca.crt: "{{ .ca_crt }}"
        ca.key: "{{ .ca_key }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/secops/talosctl-oidc
