#yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
stringData:
    password: ENC[AES256_GCM,data:O4je5iG7PbemTzoMorVifu6fjb5asLcahcpE7D446uQ=,iv:g/9EKw8lIhlWcGiEGGduuxCr7YjPl27ppYgNltUaTeM=,tag:bRkJ81B8oLWfyTJInUpHpA==,type:str]
    username: ENC[AES256_GCM,data:w4gfY1R/mpI=,iv:D6EhuAZjIlCxO6AViWOTxqAfp9bapMIpOKgd1qqqJrw=,tag:AZJqjz7dmbTJIwrrIpnggA==,type:str]
sops:
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdld1dUI0M3BkMkYvOVBh
            QXM0NXovTmJjaC85Tk85NFNLaTVrRWx1YVNvCkI1cHpWL1VrczVDN3ZqY0NrZ0VB
            WlF6aTZ6YlB5L2FqNzh4WG9FRzE3M0kKLS0tIGJtNGxUdDR6ME1wQkRwbjlBN3hG
            TWk0ZENYR29vTDhGTW4yZi9Fc2VWOUEK1E/t1vftORbzMM4EMkWxrfVWeePLwXLO
            XkiKA21guMBK0yBUFTzW1+r+HZHxb2d9kfopkiTNdxfsOVGga+o86w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T20:16:47Z"
    mac: ENC[AES256_GCM,data:YbPCN7ZZC6dKDmS3sy1dXHZoRAOy6e3uaqCCTwEVv3D5FlFttysIbFPfMdl8TkSc8z0TvhCo93gA9HH7hTIpiwUE/pGYbWHjIsb7Z7wTU0zyMQviYVtDh6BfxICRfMSQTZ/M1b/F5wkANLLeUR1i4rU+whmVPCVnmAAbn+G1Al0=,iv:Js0RgPyG9nUYD4JAERrdik8RyLTz6nt+nUnl/t7skO8=,tag:iNogNlfWwcE9+qHeE93LgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
#yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-minio
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ZzZJaLFuGRkhb6yQ,iv:9fqOU1eTo5uLzeBH3Z4CBv+b2gnCv+x3CTNl79mBVRY=,tag:1MJ3v/zyrEKs4Qxxvt7Ytg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:j720JZGyLQjfUmDCYuBB9W5I6kcgWWGIn7551Lj1F8zqUGj91sXDYOEjXCHMH6TF335DjN/yXhQ=,iv:syE0AzKFsgK+Os+o4WRhCeSqvJ3gBY2M8MJMuxY/UX8=,tag:EubemdvIwSYWBbD/UKe2zA==,type:str]
sops:
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdld1dUI0M3BkMkYvOVBh
            QXM0NXovTmJjaC85Tk85NFNLaTVrRWx1YVNvCkI1cHpWL1VrczVDN3ZqY0NrZ0VB
            WlF6aTZ6YlB5L2FqNzh4WG9FRzE3M0kKLS0tIGJtNGxUdDR6ME1wQkRwbjlBN3hG
            TWk0ZENYR29vTDhGTW4yZi9Fc2VWOUEK1E/t1vftORbzMM4EMkWxrfVWeePLwXLO
            XkiKA21guMBK0yBUFTzW1+r+HZHxb2d9kfopkiTNdxfsOVGga+o86w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T20:16:47Z"
    mac: ENC[AES256_GCM,data:YbPCN7ZZC6dKDmS3sy1dXHZoRAOy6e3uaqCCTwEVv3D5FlFttysIbFPfMdl8TkSc8z0TvhCo93gA9HH7hTIpiwUE/pGYbWHjIsb7Z7wTU0zyMQviYVtDh6BfxICRfMSQTZ/M1b/F5wkANLLeUR1i4rU+whmVPCVnmAAbn+G1Al0=,iv:Js0RgPyG9nUYD4JAERrdik8RyLTz6nt+nUnl/t7skO8=,tag:iNogNlfWwcE9+qHeE93LgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres17-role-harbor
    labels:
        cnpg.io/reload: "true"
stringData:
    password: ENC[AES256_GCM,data:+N4iygMt9MrAvnC4U390BPiIrBu8g3syrkbZrkNgwJEoKZnYGPrlmEqojvU=,iv:iya5xXeoRfnPKSmMgtWcPAJCQp2LK03yArI5+N62b0U=,tag:zOvF6n8lbO/NjmVJ02KYVg==,type:str]
    username: ENC[AES256_GCM,data:1e4Xnzhw,iv:KdFyWn/Xk9XBg7HkST2miBOZCPGa1eFomxYR2krH9Ww=,tag:6vmWh0QyQYYPRHKKt1L/0A==,type:str]
sops:
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdld1dUI0M3BkMkYvOVBh
            QXM0NXovTmJjaC85Tk85NFNLaTVrRWx1YVNvCkI1cHpWL1VrczVDN3ZqY0NrZ0VB
            WlF6aTZ6YlB5L2FqNzh4WG9FRzE3M0kKLS0tIGJtNGxUdDR6ME1wQkRwbjlBN3hG
            TWk0ZENYR29vTDhGTW4yZi9Fc2VWOUEK1E/t1vftORbzMM4EMkWxrfVWeePLwXLO
            XkiKA21guMBK0yBUFTzW1+r+HZHxb2d9kfopkiTNdxfsOVGga+o86w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T20:16:47Z"
    mac: ENC[AES256_GCM,data:YbPCN7ZZC6dKDmS3sy1dXHZoRAOy6e3uaqCCTwEVv3D5FlFttysIbFPfMdl8TkSc8z0TvhCo93gA9HH7hTIpiwUE/pGYbWHjIsb7Z7wTU0zyMQviYVtDh6BfxICRfMSQTZ/M1b/F5wkANLLeUR1i4rU+whmVPCVnmAAbn+G1Al0=,iv:Js0RgPyG9nUYD4JAERrdik8RyLTz6nt+nUnl/t7skO8=,tag:iNogNlfWwcE9+qHeE93LgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
