---
volumes:
  config:
    external: ${VOLUME_EXTERNAL:-false}
    name: ${VOLUME_NAME:-openssh-server_config}
    driver: ${VOLUME_DRIVER:-local}
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/tmp}

services:
  openssh-server:
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - AUDIT_WRITE
    scale: 1 # scale to 0 if you want to stop the service without losing data
    container_name: ${CONTAINER_NAME:-openssh_server}
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TZ:-Europe/Vienna}
      LOG_STDOUT: "true"
      USER_NAME: ${TARGET:-linuxserver.io}
    image: lscr.io/linuxserver/openssh-serve:10.3_p1-r0-ls233@sha256:96b9a4d3b5106746d08d43a6911650d4d21f7d5c7f2ac9660e792bdb5e63157c
    ports:
      - ${SSH_PORT:-2222}:2222
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - config:/config
      - data:/data
