---
networks:
  apps:
    name: apps
    external: false
services:
  minio:
    cap_drop:
      - ALL
    command:
      - server
      - /data
      - --console-address
      - :${CONSOLE_PORT:-9001}
    container_name: ${CONTAINER_NAME:-minio}
    image: pgsty/minio:RELEASE.2026-02-14T12-00-00Z
    env_file:
      - ${SOPS_ENV_FILE:-sops.env}
    environment:
      TZ: Europe/Vienna
    healthcheck:
      test:
        - CMD
        - /data/mc
        - ready
        - local
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - apps
    ports:
      - ${API_PORT:-9000}:9000
      - ${CONSOLE_PORT:-9001}:9001
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    volumes:
      - ${DATA_PATH:-./data}:/data
