---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/forgejo-system/forgejo/admin

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      # chart consumes these keys as GITEA_OAUTH_KEY/GITEA_OAUTH_SECRET
      data:
        key: "{{ .client_id }}"
        secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/forgejo-system/forgejo/oidc

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-db-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/forgejo-system/forgejo/db

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-data-volsync-minio
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/volsync/forgejo-data

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-dump-s3
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_URL: "{{ .S3_URL }}"
        S3_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/forgejo-system/forgejo/dump
