---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./replication-destination.yaml
  - ./replication-source.yaml
  - ./helm-release.yaml
  - ./http-route.yaml
  - ./ssh-tcp-route.yaml
  - ./dump/cronjob.yaml
