---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: &name forgejo-data
  labels:
    # https://fluxcd.io/flux/components/kustomize/kustomizations/#controlling-the-apply-behavior-of-resources
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    repository: forgejo-data-volsync-minio
    copyMethod: Snapshot
    volumeSnapshotClassName: local-nvme
    cacheStorageClassName: local-nvme
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 2Gi
    storageClassName: local-nvme
    accessModes:
      - ReadWriteOnce
    capacity: 50Gi
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
