---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: v2.2.1
    digest: sha256:e38a8a95dd6c7806e20433cfdbe36946fbfe196684b790a6a1fc451177b0fa57
