---
apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: firecrawl-nuq
spec:
  credentials:
    usernameSecretRef:
      name: firecrawl-db-init
      key: INIT_POSTGRES_USER
    passwordSecretRef:
      name: firecrawl-db-init
      key: INIT_POSTGRES_PASS
  databaseName: firecrawl_nuq
  databaseServerRef:
    name: postgres17
    namespace: cnpg-system
  prune: false
