---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firecrawl-db-init
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_USER: "{{ .NUQ_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .NUQ_DB_PASS }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/ai/firecrawl #gitleaks:allow

---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firecrawl-env
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BULL_AUTH_KEY: "{{ .BULL_AUTH_KEY }}"
        NUQ_DATABASE_URL: "postgresql://{{ .NUQ_DB_USER }}:{{ .NUQ_DB_PASS }}@postgres17-rw.cnpg-system.svc.cluster.local:5432/firecrawl_nuq"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        SLACK_WEBHOOK_URL: "{{ .SLACK_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/ai/firecrawl #gitleaks:allow
