---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name otel-collector
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_BEARER_TOKEN: "{{ .OTEL_BEARER_TOKEN }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/observability/opentelemetry
