---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-secret
spec:
  target:
    template:
      data:
        HA_TOKEN: "{{ .HA_TOKEN }}"
