---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opengist
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OG_SECRET_KEY: "{{ .SECRET_KEY }}"
        OG_OIDC_CLIENT_KEY: "{{ .OIDC_CLIENT_ID }}"
        OG_OIDC_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/git-system/opengist
