---
services:
  busybox-enc:
    scale: 1
    container_name: busybox-enc
    image: busybox:1.38.0@sha256:b6762ddf4a50aabb5f4d21aa6f447d05d5633fb09f09c08b33f22356a2f98be0
    env_file:
      - ${SOPS_ENV_FILE:-sops.env}
    command:
      - sh
      - -c
      - |
        echo "hello from doco-cd target=${TARGET:-undefined}"
        echo "decrypted secret value: $${DEMO_SECRET}"
        sleep 3600
    restart: unless-stopped
