---
services:
  busybox-enc:
    scale: 1
    container_name: busybox-enc
    image: busybox:1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
    env_file:
      - ${SOPS_ENV_FILE:-sops.env}
    command:
      - sh
      - -c
      - |
        echo "hello from doco-cd target=${TARGET:-undefined}"
        echo "decrypted secret value: $${DEMO_SECRET}"
        sleep 3600
    restart: unless-stopped
