---
services:
  busybox-enc:
    scale: 1
    container_name: busybox-enc
    image: busybox:1.37.0@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
    env_file:
      - ${SOPS_ENV_FILE:-sops.env}
    command:
      - sh
      - -c
      - |
        echo "hello from doco-cd target=${TARGET:-undefined}"
        echo "decrypted secret value: $${DEMO_SECRET}"
        sleep 3600
    restart: unless-stopped
