---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./storage.yaml
configMapGenerator:
  - name: scanservjs-airscan-config
    files:
      - airscan.conf=./config/airscan.conf
generatorOptions:
  disableNameSuffixHash: true
