---
name: node-exporter
working_dir: docker/deploy/node-exporter
---
name: olah
working_dir: docker/truenas/olah
env_files:
  - .env
---
name: arcane-agent
working_dir: docker/truenas/arcane-agent
env_files:
  - .env
