# ---
# # For testing only
# name: busybox-enc
# working_dir: docker/synology/busybox-enc
# env_files:
#   - .env
---
name: node-exporter
working_dir: docker/synology/node-exporter
env_files:
  - .env
# ---
# name: minio
# working_dir: docker/deploy/minio
# env_files:
#   - synology.env
