---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ollama
  description: Ollama is a self-hosted runtime for running and serving large language models locally.
  links:
    - url: https://github.com/tyriis/home-ops/tree/main/kubernetes/main/apps/ai/ollama
      title: Flux definition
      icon: github
      type: github-repository
    - url: https://github.com/ollama/ollama
      title: Upstream Repository
      icon: github
      type: github-repository
  tags:
    - ai
    - llm
    - machine-learning
spec:
  type: service
  lifecycle: production
  system: main-cluster
  owner: home-ops
  dependsOn:
    - component:envoy-gateway
