# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gcpsm-credentials
    namespace: secops
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:TIEBUOX/Vp7RFjxXt39j447QhU0ScQRliMwOzOeNhi+McaOHyk9eKqRE2kaCJfeRibLyf8Hmk7a3pnIHkS/MpuntHNNS7tZ9YUhsIwxf1jaNERs0E361FuOEMgLfor4/VKA1XyKktEHj5iKD/DnrQAEROaPMK73k7oKOp/5u0Rot/uZ6JDxDzvoQ3BSzrL1YwjEL/PELxGQaLiwcjHtbbV1KVQ7Js8BLsSO4ni2/x0AMk0ebqQScRWtkOSd/WIgJPygvAb7zsfxU1Op+jv9qzoNCirGBCjTboNshfpfH51xiXk+UIaJRp0xCWWiq9IlHt/+/PDri+C9OjmWfizbNOuRcwojcTKiyrEX8iS174pAMopuzHx/HFii4I4Sx8MEoSuzpQWf63CtlBlZx++aS5MxwuSTkGofasXP6IKeOS7NjCugY7uGzYyKf7oWof9hXnv/KQbXYlI/KvQxrwIlMW8mkn8LP5w0BGpiIbH9M0C5xRjw+Xaz/PHadBLrck2aZ6cz3+Kn3IoMrBLG1A6NJcsDJSRwbvslaRw6jsWB9QuooP9lhSONG40e/Q8E6wGpHdN/LvFWWHGwFgDCIBZ0BQDLkgX9UzNrDPnADlq4Db5ZUjkaDi42GUqALvkHz39J7QthPSfm+bjWJgV/N8m19z4nNFIq1oRNIu7qZ5xQ3q1e1ciy3adcvqvkuS9Ch4ndvjG0EFxST+sgGk2IY0EsNo+8E8LDUut4FzocErNkiVpKhX+oYzqUSyfmmRd6kitbU7JyS17AFuW1BSpi1tuvXyQatEixz1YacxQ6cNTLRJ3qKCMZkpM6XGO9JwUKElftwGg01zJm9/Ky/YKJkLm0wLDweg73MzhH/RkAfVe+kUmuuDyylgfklKZH8c5riAO8Ujpxy+UkE5BtK0bp0ddV3xL3hO8glJK3jZFHZhDM=,iv:ur0jPVSJDKwJCkX5qB+4Og21yCXij6ycqUEKzv14+iQ=,tag:wfjchqqgQufZmBb7lUVRMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUy8zbWdsQmppYmFZcHpZ
            UXNHeG9wRHdtY0NhNVUvZUhQSzdzYkNXOXhJCnY1QUVoUXpxUzBWSDVhOEpTdURj
            TTRjSWFxV1FZUUlNUktvSUJPTnVjaDAKLS0tIFkyQU1ISm5uWVFPRFpzWExMWXU3
            Q0JBOFBiMWdMc3ByaWhUeGhveFY5eDAKZqJThTK868dontuY2JvcoihU7EiI9JOE
            nl5xJuVqGIZjbvCJTpHFovQ9ts+9W4nLXinBtBSx5gDnv7S6mHhPeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T20:56:33Z"
    mac: ENC[AES256_GCM,data:Z+KX6xOZju7WY1+WcXTiskxwr5BkPhGbbst8lC1uF2I/EWlmugpI+2pef9I/A2RXrfg6hty96dOLD0mPxDXYc/tlFu61myFYmBLx+jDYVFekK0ihCmN8iF3U6y6nbHpLFUXeVyRRNbNxjD8/zFo3HCXlAJ9pJL79dkGtHBU4Ldg=,iv:EyW/3zMIlpTtZ3Zhdv5c7HurKL+Twv6efhsQwnfPfzA=,tag:02Q4bPakw0WrOA5aHi2jIQ==,type:str]
    version: 3.13.3
