---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcpsm-backend
spec:
  provider:
    gcpsm:
      projectID: techtales
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-credentials
            key: credentials.json
