{
 "title": "Network devices",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Alex PC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum_over_time((opnsense_dhcpv4_lease{hostname=~\"gameboy|gameboy-wlan\"} == 1)[24h:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dominik PC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum_over_time((opnsense_dhcpv4_lease{hostname=\"techinik-PC\"} == 1)[24h:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dominik TV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum_over_time((opnsense_dhcpv4_lease{hostname=\"techinik-tv\"} == 1)[24h:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alex pc",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "opnsense_dhcpv4_lease{hostname=\"gameboy\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "dominik tv",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "opnsense_dhcpv4_lease{hostname=\"techinik-tv\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "alex mobile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "opnsense_dhcpv4_lease{hostname=\"alex-a54\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "dominik pc",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "opnsense_dhcpv4_lease{hostname=\"techiniks-PC\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "dominik mobile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "opnsense_dhcpv4_lease{hostname=\"A54-von-Dominik\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}