---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tempo-s3
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: "{{ .S3_BUCKET_NAME }}"
        S3_BUCKET_HOST: "{{ .S3_BUCKET_HOST }}"
        S3_BUCKET_REGION: "{{ .S3_BUCKET_REGION }}"
        S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/observability/tempo #gitleaks:allow
