---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: opentelemetry-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator?modal=values
    admissionWebhooks:
      certManager:
        enabled: true
    manager:
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
