---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name immich-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1@sha256:392b53675b403d6a2c72b673cc488a7c272514755dd818c622fb9ce4665193c4
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: local-nvme
  enableSuperuserAccess: false
  postgresql:
    shared_preload_libraries:
      - vchord.so
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      secret:
        name: immich-db-init
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS vector CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: *name
        serverName: *name
