---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mosquitto-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Value is the full mosquitto passwd file content, e.g.:
        #   homeassistant:$6$...
        MOSQUITTO_PASSWD: "{{ .MOSQUITTO_PASSWD }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/home-automation/mosquitto
