---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-env
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://gethomepage.dev/installation/#security-authentication
        HOMEPAGE_AUTH_SECRET: "{{ .HOMEPAGE_AUTH_SECRET }}"
        # HOMEPAGE_AUTH_PASSWORD: "{{ .HOMEPAGE_AUTH_PASSWORD }}"
        HOMEPAGE_OIDC_ISSUER: "{{ .HOMEPAGE_OIDC_ISSUER }}"
        HOMEPAGE_OIDC_CLIENT_ID: "{{ .HOMEPAGE_OIDC_CLIENT_ID }}"
        HOMEPAGE_OIDC_CLIENT_SECRET: "{{ .HOMEPAGE_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/${NAMESPACE}/${APP}
