---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: media
type: Opaque
stringData:
  DB_USERNAME: immich
  DB_PASSWORD: immich # NOSONAR devenv only
  DB_DATABASE_NAME: immich
