---
services:
  node-exporter:
    command:
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
      - --web.listen-address=0.0.0.0:9100
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.11.0@sha256:2f0cc335ef9ea15d6c96e1c0d693d8b57c0b794d0244b22313a6c162bd1cb1b8
    network_mode: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /:/host/root:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  smartctl-exporter:
    scale: ${ENABLE_SMARTCTL_EXPORTER:-1} # scale to 0 if you want to stop the service without losing data

    # container_name: ${CONTAINER_NAME:-doco-cd}

    container_name: smartctl-exporter
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0@sha256:cfe22c36d7d2fac48ebf619707305acb65eb0fb670656eb80f356e606d782bc1
    ports:
      - 9633:9633
    privileged: true
    restart: unless-stopped
    user: root
