# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: harbor-credentials
stringData:
    password: ENC[AES256_GCM,data:MGKT5yYswHZoVQCTE00uZ9JX6TFtyo7YXLTKKLXPYDd7RkPpKacwJ+rY7zQ=,iv:r7MyA3m3x/ox5LVKTmi1euiLEKhFn4XTO7W8DC9c9FI=,tag:bMYjRcJW14kB9KWl+NDyuQ==,type:str]
sops:
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzRWUkxIMnA1Nm5MSFVP
            anliQ3F3R1VyWVVNak5mUm5ST3dsSnFRY1hrCkpONU50NGsyUWlhNkYyL3lqN1h5
            VXdSZ0g2NnFsS0loMERMWmZIbGdob28KLS0tIE83RHBlY2FYd0F0YklBRThQd2tl
            TVM4dVYwY3ExYkIxSmJoK3V5VEJNQ2MKs9lDocwW5M7BmdvfvOABbjuffo16CJok
            djKyN7RS86g3cstMR5X4uKoC+UFS6F4+xkNVtJoc6mZS71ZN4RU2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:41:56Z"
    mac: ENC[AES256_GCM,data:T/69BDMAMn1IL1yseaOw2CBq1y0i1ihmWtYmVFPO9XyErp/v8orj0s4a9VHATDPbfk7BF24hhV0Jvh/IFlRh3Kt+8SssS4NCCQUe3Nb1gw98tEnzcvlbVNqPh4l04h4vB2bg3yGkekAaNQchwCBiTp5nVToQU/T8PsMSiAzOPOs=,iv:mNodyc5MssUe1iyGLyHK9Ut2t0yUkj9USySI+DJWQWM=,tag:4WSFKjlgVETihRaO1rfTzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: harbor-encryption
stringData:
    secretKey: ENC[AES256_GCM,data:ND4tljlvuPmXexRtEg+POw==,iv:dU7wfnrB5rGURB1cEZu2dis8mut/ShdxfrQIYnUE0Cw=,tag:V2szKXgCb+MVNrzsBGOt+A==,type:str]
sops:
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzRWUkxIMnA1Nm5MSFVP
            anliQ3F3R1VyWVVNak5mUm5ST3dsSnFRY1hrCkpONU50NGsyUWlhNkYyL3lqN1h5
            VXdSZ0g2NnFsS0loMERMWmZIbGdob28KLS0tIE83RHBlY2FYd0F0YklBRThQd2tl
            TVM4dVYwY3ExYkIxSmJoK3V5VEJNQ2MKs9lDocwW5M7BmdvfvOABbjuffo16CJok
            djKyN7RS86g3cstMR5X4uKoC+UFS6F4+xkNVtJoc6mZS71ZN4RU2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:41:56Z"
    mac: ENC[AES256_GCM,data:T/69BDMAMn1IL1yseaOw2CBq1y0i1ihmWtYmVFPO9XyErp/v8orj0s4a9VHATDPbfk7BF24hhV0Jvh/IFlRh3Kt+8SssS4NCCQUe3Nb1gw98tEnzcvlbVNqPh4l04h4vB2bg3yGkekAaNQchwCBiTp5nVToQU/T8PsMSiAzOPOs=,iv:mNodyc5MssUe1iyGLyHK9Ut2t0yUkj9USySI+DJWQWM=,tag:4WSFKjlgVETihRaO1rfTzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
