---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tuppr
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://github.com/home-operations/tuppr/blob/main/charts/tuppr/values.yaml
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
