---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  DB_HOSTNAME: postgres17-rw.cnpg-system.svc.cluster.local
  REDIS_HOSTNAME: dragonfly.dragonfly-system.svc.cluster.local
  IMMICH_MEDIA_LOCATION: /media
  IMMICH_MACHINE_LEARNING_ENABLED: "false"
  IMMICH_SERVER_URL: https://immich.techtales.io
