---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      postgres:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/postgres
              tag: 16-vectorchord0.4.3-pgvector0.8.0-pgvectors0.3.0
            env:
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_DB
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_USER
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_PASS
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              runAsNonRoot: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
            envFrom:
              - configMapRef:
                  name: immich-config
            env:
              DB_HOSTNAME: immich-postgres.media.svc.cluster.local
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_USER
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_PASS
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-init
                    key: INIT_POSTGRES_DB
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      postgres:
        controller: postgres
        ports:
          http:
            port: 5432
      server:
        controller: server
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          external-dns/unifi: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Photo and Video Management
          gethomepage.dev/group: Media
          gethomepage.dev/icon: immich
          gethomepage.dev/name: Immich
        hostnames:
          - immich.techtales.io
        parentRefs:
          - name: envoy
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: server
                port: *port

    persistence:
      postgres-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: local-nvme
        advancedMounts:
          postgres:
            app:
              - path: /var/lib/postgresql/data
      media:
        type: nfs
        server: nas.techtales.io
        path: /mnt/tank/media
        advancedMounts:
          server:
            app:
              - path: /media
      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /tmp
