---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.0.2@sha256:14390f3dc9512dc3273b12ccee6363d9be16c388699abc3f3fe0498bb9829937
            envFrom:
              - secretRef:
                  name: immich-env
            env:
              DB_HOSTNAME: immich-db-rw.media.svc.cluster.local
              REDIS_HOSTNAME: immich-dragonfly.media.svc.cluster.local
              IMMICH_MEDIA_LOCATION: /media
              IMMICH_MACHINE_LEARNING_ENABLED: "true"
              IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003 #NOSONAR allow http
              IMMICH_SERVER_URL: https://immich.techtales.io
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.0.2@sha256:412f68e46e1966d0f87a8733a430369ee184b3a83e7b1e2db536dff291a34aa7
            env:
              TRANSFORMERS_CACHE: /cache
              HF_XET_CACHE: /cache/huggingface-xet
              MPLCONFIGDIR: /cache/matplotlib-config
            probes:
              liveness: &mlProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlPort 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *mlProbes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *mlPort
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      server:
        controller: server
        ports:
          http:
            port: *port
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003

    route:
      app:
        annotations:
          external-dns/unifi: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Photo and Video Management
          gethomepage.dev/group: Media
          gethomepage.dev/icon: immich
          gethomepage.dev/name: Immich
        hostnames:
          - immich.techtales.io
        parentRefs:
          - name: envoy
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: server
                port: *port

    persistence:
      media:
        type: nfs
        server: nas.techtales.io
        path: /mnt/tank/immich
        advancedMounts:
          server:
            app:
              - path: /media
      ml-cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: ceph-block
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
