---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_ALLOWED_CHANNELS: "{{ .DISCORD_ALLOWED_CHANNELS }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
        FAL_KEY: "{{ .FAL_KEY }}"
        OPENCODE_GO_API_KEY: "{{ .OPENCODE_GO_API_KEY }}"
        OPENCODE_ZEN_API_KEY: "{{ .OPENCODE_ZEN_API_KEY }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/hermes-agent/${APP}
