---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .ADMIN_USERNAME }}"
        password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/git-system/forgejo

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: "{{ .OIDC_CLIENT_ID }}"
        secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/git-system/forgejo

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-db-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .PGUSER }}"
        password: "{{ .PGPASSWORD }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/utility/git-system/forgejo
