---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  pr-merge:
    desc: Merge a pull request safely using a standard merge commit (NEVER SQUASH)
    summary: |
      Merges a GitHub pull request using a standard merge commit.
      Usage: task git:pr-merge -- <PR_NUMBER_OR_URL>
    cmds:
      - gh pr merge {{.CLI_ARGS}} --merge --delete-branch
