---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://bjw-s-labs.github.io/helm-charts/
