---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-controllers
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
spec:
  endpoints:
    - port: http-prom
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux
