---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gatus-rules
spec:
  groups:
    - name: gatus.rules
      rules:
        - alert: GatusEndpointDown
          annotations:
            summary: The {{ $labels.name }} endpoint is down.
          expr: |-
            gatus_results_endpoint_success == 0
          for: 5m
          labels:
            severity: critical
