---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name n8n-env
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        N8N_INSTANCE_AI_MODEL: "{{ .N8N_INSTANCE_AI_MODEL }}"
        N8N_INSTANCE_AI_MODEL_API_KEY: "{{ .N8N_INSTANCE_AI_MODEL_API_KEY }}"
        N8N_INSTANCE_AI_MODEL_URL: "{{ .N8N_INSTANCE_AI_MODEL_URL }}"
  dataFrom:
    - extract:
        key: infra/kubernetes/main/home-automation/n8n
