---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  interval: 30m
  timeout: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-charts
        namespace: observability
      interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    server:
      replicaCount: 1
      retentionPeriod: 30d
      image:
        tag: v1.53.0
      persistentVolume:
        enabled: true
        size: 20Gi
        storageClassName: local-nvme
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
