# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-tokens
stringData:
    VMAUTH_TOKEN_MAIN_CLUSTER: ENC[AES256_GCM,data:+bkPZ6zCrSrOsgx3/LpoWkytNM2VM+jbxSrccXHtHmRJeg7u/NY+86PnRMKJuFbZsGRuj3K5FYcfZkmmMo+u5g==,iv:EjhAw4o0MGnT6g9pUIX5t1bBfWkJb1ObNSqpPQvelC0=,tag:BgZikGD0A1tA5yVaMANPCQ==,type:str]
    VMAUTH_TOKEN_UTILITY: ENC[AES256_GCM,data:ejDyL0AmmfvCYBGSn+sk80eofArlbbWiuvN1iSNMkgNUOy5H1haCXRsyXvKMTpcMYnMxMOkEYE9kWhBSYXcarw==,iv:MRy9jmo4hRomz/EHpuzJou5pWuncn19jkQLrkFGLjHA=,tag:U/bdjYcFf1jaNdQubPWeCQ==,type:str]
    VMAUTH_TOKEN_NAS: ENC[AES256_GCM,data:QdfA8PNHWVFaT69SG2nD/LSLbnNyVvs2m0MWWnd3PBLpQ49K9JWN5TAGo464PeFJT/INGfl8gYO+EXO0TRuRsQ==,iv:txhIXDMpFJPc9wPzEE+pNQhP2ZB1KbRR/DARWzaWxpg=,tag:cSIcPgE6mbdJex99K5fJ0w==,type:str]
    VMAUTH_TOKEN_BIFROST: ENC[AES256_GCM,data:G8Sg2uAZrfAALiY1NMUWOS//yTe70V9ZWFKUwp3mV4AHM5h+KlHe3UMuROgnXR5tMF7dRE9/eUh/CYWC1IRn0w==,iv:rn/7KzKzVRmIvr6KWoJ0LgLSlYhbzCibCzdlDB+a2Bk=,tag:zQB4t84XqmByICaq7RoNeg==,type:str]
    VMAUTH_TOKEN_RED: ENC[AES256_GCM,data:74/X64FJEBRqk0VVQqo91+6UL18CMTrsWpq8cvYR2SMDSoPJVEbK6VJWrKzy28EJaoEdfpEeY3aSaRo4uCfVgQ==,iv:RzA52Q//i6MZPQaRzJ4ig3oq/h+WDjQ22L57beR9S0Q=,tag:caHq6kMzy34CaT3QoAsmww==,type:str]
    VMAUTH_TOKEN_PURPLE: ENC[AES256_GCM,data:3zzdyqiGM1ObL463DMx+ZYncc56umEF+7laAlR8F6bVKOLvO3ezFc98GQ9/7ySNcJGlGyaUDLkcUMWdVOgQdWw==,iv:AjrvWVIkaXKF5RvVM5GwqtaxqZRIum9wu28qveXcZOA=,tag:XckCFY+vFHPBDCJdkw9oog==,type:str]
    VMAUTH_TOKEN_SYNOLOGY: ENC[AES256_GCM,data:4auH0eTfboAoCCblbNjJOuaqPzBy8FAYzAVhFhzp/+U8kZq8ur4C1oSXuGvKTv+JcM2+qoXSi1VmMt+CrH3ZXg==,iv:keLUJn+nrxFfVrkhrydS0ChyFylSsl+syIoZDP83Nkg=,tag:NVKrka6iDkEnJBwyruk1eA==,type:str]
    VMAUTH_TOKEN_GRAFANA: ENC[AES256_GCM,data:aHOKflDOzH03Aq3RipqrOYftb8Gglf8MnKGKsUezKgvGbwIzaZCBvP0P+TptP5GEt33sLyuDfs9ysPJcPXkjYQ==,iv:1kh4ysDx/J/v1J2gGoMGE6zNiX8fpXXAZM17GjVho1I=,tag:XHTgO8QWAQ7GUK1SPfl1Fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRzRmNEFGWGRUeDViWVJo
            Y0FzWWg1am5MZlN2cVFYaGNickhoa05sWWtJCi9nU2VHcmVaZWdFRXN1QVZoOGtI
            R2VEWUFwL0lsUkRRUUF1QkNNN0JKRTAKLS0tIENaVCtIWklNMkNocmZDalBqUitq
            MEJwbHU4Q0ZWNklEOGRqUjdFYTk0clkKld+QTRI4L3SjXJ8E7/EN0SvVMmklhe0O
            z5rQHO9zmGjBSPHHzMRO9leI0Y5JdO4AllCCguA/4QPps6sI9clGcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-11T00:21:10Z"
    mac: ENC[AES256_GCM,data:MPGBIsunjgCiFKmLKgccm30FxJDWaIR19/W/q5FixJ2flv20SUP4xw0REcHNhSG1eub73unRkWgnuxgOJy3d1IHUYrIDkh9o2PgTaVkU3/cM3eYNRtwplQXIgG/VdAkwaurpWKwTkWh5KjYg0pVsp358ciboh0kO5pRu/H9b9bY=,iv:zEZPWq11keJP3TfZlFQmFgePyhXA3DLTqxLxR2DB8JQ=,tag:UgCCE1TUkylZHvXh+Lq/Ng==,type:str]
    version: 3.13.3
