# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-tokens
stringData:
    main-cluster: ENC[AES256_GCM,data:PBBp2j+N27FFAcYWGhsiPiw/siYmn5kvlMiMkWA8kF8k9sAZWlby4lWWo7wUPTRUfrEhokbqdZX4Xtba6ek4uA==,iv:vdCNDj7RIBTsBUU9MLQNcgUJQ+0OcQLyujXGhiFHXbI=,tag:B+HayT9/v061dOel1iJgCA==,type:str]
    utility: ENC[AES256_GCM,data:ywaEkeJuFeYNFXDBc+FPunckMbsGqalspZZ3NpsWrh/DzmgL8/doK0BA3d7eieWSpkqhyovDTvrIl39/80Se0Q==,iv:SeCyXp+Y4FctJftWmmtBqcth5388ad6gDtJ/u3reCwE=,tag:PxKr1dB0dKQ8RiFKChLJlQ==,type:str]
    nas: ENC[AES256_GCM,data:2Hh6jIkIFQW/doxfNGmfMFEsJLPoKC8PiH8rCaSrh4THKowtVlCJRthzjG+c+zIXgH60DIiELe7oHckWGpiu5g==,iv:Z+ctdVElDZXJsvAZFXxbMnUpQJ/mpDwu8Ruem4x+8dc=,tag:sfZI7Nc8Iw+JDEX/gWnrGA==,type:str]
    bifrost: ENC[AES256_GCM,data:17WIYi91s79PyqIf3sV63+fXqZD/swG8j/Y2fX8uK/cRgRvKiodQtbjWMgiuxs/5qoKZ+RpDU/kY83O9dNWbPw==,iv:hS9e5G+5d1nyN1lQjma3NIMD2MWS5sQuvjaIIHizAmM=,tag:8Ow5w2k61x70pXxnWbwttA==,type:str]
    red: ENC[AES256_GCM,data:9dlPVnaRL1gGuFLNqtOPnzKuoQYX02/3UGgdxpBsjFHDL7oRtXQ2DBaXkBdL3a7pN2JIcK32+HeoJ+EKnazfgg==,iv:Be8JBpx/g7DIGfudAu19G9/heKc94pqWK0Dl6xmbqEw=,tag:ZF+V9uZ8KrxlobSR8BXNTg==,type:str]
    purple: ENC[AES256_GCM,data:dwgZas2qAUYVfQFf+8qs8NuJS+KLKKMz2gV1UNv62d3/wVcg9Tm6fUB2pRvTxSDBMLOr4CeA1U25/4jtgdZaoQ==,iv:T8gOqX1OUZva/DDX7bTztHn5kg8kViNr5Pzmu/90Q+A=,tag:ypMOjfyOVL8JvucCaAWmzw==,type:str]
    synology: ENC[AES256_GCM,data:uQ+fJzJIoNR+UJbHa0+c3rGSczaipK6Nxm2DOtEUj4LQbV0YV0WXuyq1xJHJ1U5RN7FssgfksXIWjoUI0kajtg==,iv:YP6ozIEbm3mlXEzB54eeo1k/x9+/81jk43MgL7boCaU=,tag:kdOCFw3mFU5jAZkw4tPh+w==,type:str]
    grafana: ENC[AES256_GCM,data:KOSzh/wXmHzBOLUeAUde73x3c5vCyGt6kRyLCE7efvoz9LBccjxBYcBIWnOkgEq8m3JcWvU4yzwHHbLgJOOd+g==,iv:FdxKKtkKOLJua1ZbmpTOGCC3Mgop5cG/D5qHyO6gwmI=,tag:1J/NeOemwYAz1otUGldg7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnU2UDA4ZU1zZ0ttNW9u
            UnNEYURoK3B2bjBtalUrYVVlZVhUTDAra1NZCjYvZzlkYVNpYlJSYXoxbDJjWEFz
            azNJbzM4OE1zSytxSzBscWRNcWFFcm8KLS0tIHJMTEljZlRlQ3hEdGk4UFNWa2l0
            cFZuYUxndkludUNEVDJpWkFCMUlyVXMKM6WSbEseORwzvPDNhTfquog1RndPVNt8
            dbo00GR826W/gXADS32RZLSwSliPnAm+JwqJoYI4v6gx38s5ZiRLxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-11T00:03:09Z"
    mac: ENC[AES256_GCM,data:HY3R06Bvq5AeJncq4HrGKyG7F4A7yr4PCfPjEK/tK9MR9DGSHrMLT18op5vFIA7IA4EZZ4fqmiknv0B4UG3RtnOtyKOfACT8XbQBv2HzqKZO3qZDLAWoO2dNdDUUJW9mj9Vc5/qKADSYS9lNrqA7d5G1Iu2fROMC7ScPuEWs2e8=,iv:aspHC3WcAHCb0vSOOZMB2mxWw/iTIZd30gFGzFBGFsA=,tag:IrPHSoJ0EuRyr+YCb+wXIQ==,type:str]
    version: 3.13.3
