# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-ms01
stringData:
    token: ENC[AES256_GCM,data:pAL9V+cdTwSkdaT0PiakT7ZXO/FySIVcISXM6kubTv6YTNk3gM92JA0g6lA7ItTNpA6VnA3pkqMnIogHMhrkPQ==,iv:vTlTtuoC/hWkmGypqWZdtO1wAHEpvNu0JFjqi08/+7k=,tag:4JIOajzoQOKCsPLIVEVFfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-utility
stringData:
    token: ENC[AES256_GCM,data:+1X/HWH+T+I3gH3hjT0gnNMSMGYACJu/iF+E3OYk4tx75M7bISJilmGiYZjfkLHygLZRw2nrZqE2vahOHm2ItQ==,iv:/xAHot+h/ct2+tQszlybJDJ3IHCwV7umNYHYoHz1fvE=,tag:8/Gu5wcRl2Ss/hDb2Ao5fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-nas
stringData:
    token: ENC[AES256_GCM,data:ftqFI61QEyQhNXGieIw9IQ4+KKp3GB/rWlt49Ck5rVakdGFVQ6KNMJgHK99kHQdgD12QOvORnT2SqkbnPhwTEA==,iv:owRtd1+yaxck6loe+Rzy2S3KppSKyCouFtiY4zsTcLw=,tag:dzsMNilJ2g4APuPpxuPqcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-bifrost
stringData:
    token: ENC[AES256_GCM,data:G4Q4tQKdPCjGbl8uCry7RWRLn70sBDrPfTow1XfWBnJvZRooOsMBGENDBPykU2Y9RdpZ+UXOJG9GgJ0y55DJoA==,iv:IDZ4akPw8UUkzLYX/EwYqYE7/cJzmEzWmmkU7b6vHLc=,tag:VehgKRM7EOVuR0GzGkzemw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-workstation
stringData:
    token: ENC[AES256_GCM,data:oCT8UbVSu2CjjdhbZyGdWQxYltJtX9Xe6GCRGAT2+SMSw/j7lRJqkbsANRHN3KPimy0w+iGVMZoCTvKF/XlPdQ==,iv:Z9twRvEV6DBK2KhpI0wfxcwxqd09/Jxpef9hxdShCJ8=,tag:M0dkBcguSBHf6EF0ihXpNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-remote
stringData:
    token: ENC[AES256_GCM,data:cqYwVgslFiISX+5XqcrdMvBuuOY/mfKZnS4LtDL9YYo9x/iipIynPiZ7D6Kce3+WGtpJ9WGO7MEin+GnFrGKfQ==,iv:peXvLu7my0NIc+zI7+uqdfBW++dxqCbLHiscHW+yv5o=,tag:+wUdAus4qpP7Y/nJB3Nifw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vmauth-token-grafana
stringData:
    token: ENC[AES256_GCM,data:m4OPrQ9QrD3E04P3JC9cMUYBST2WTzmeBudQIEzmdoQmiOH2pEx9XV5oJ1RpW22zIDBXWNEudzRhnvyArfrsEA==,iv:S+cflpw1cnoMngo1dijus2+GXD6EbnTDt091A6HVYGI=,tag:DkUaWwmyv+Io4vZmfHKkOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG42RGtXMlhyeDNMeW15
            VlNwdkZIVTFoZHY4WHV2ZlFaZDRhbmtLT2tJClFYaXNuSnJzSHpCUHhGREdsM2hj
            WSs0WDJFVUYrTFlaUmRqeW9xZHpHOVkKLS0tIHA4emIrQVVlOGs5YUMyaXBNZjZu
            cjRvaGM0dnVKeTlzTEFONE04aVFrY0UKaqHMJ0f2bcrBtBwuZsRw8jEU8SwJR2W7
            LY1TI2m2HkhaDYEjiyy8Xn3X+RIVCsBrhzCmPZ4VUQlDG5KhC8xgHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T23:45:45Z"
    mac: ENC[AES256_GCM,data:ruL8g0S8NUCHKUvczzks5RaOHmT/LYtXKa7oe1CGCZu751vO/2hil77b5L5t6gTFxIbSoJeU4AeLnWlGtxBuEKRYHXvyLJ2XyUME8NQ9lRin1oBy/hMEeiIOBDMHP+u+XFoYvdc8K1lrsTaEqimhYZNtuYr1MfZ/eINsR3IxlnU=,iv:GpszUeveEcETd0iyDelBkp2ndJDzYbWK9jFdp+P3etU=,tag:x+whMIKx8KAt9lbqVxtBmw==,type:str]
    version: 3.13.3
